version: "3.9"
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8011:8000"  # porta diferente da raiz para evitar conflito
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings